### ISSUE TITLE
Error On payment.

### ISSUE THREAD

**Issue by mjafartp** [PurpleSoftSrl/sumup_flutter_plugin#1]
Error found on LoadSumUpPaymentsActivity.java line 473

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.sumup.merchant.api.LoadSumUpPaymentsActivity.createAffiliateResponseIntent(LoadSumUpPaymentsActivity.java:473)
       at com.sumup.merchant.api.LoadSumUpPaymentsActivity.sendAffiliateResponse(LoadSumUpPaymentsActivity.java:577)
       at com.sumup.merchant.ui.Activities.CheckoutAPIDrivenPageActivity.onBackPressed(CheckoutAPIDrivenPageActivity.java:243)
       at com.sumup.merchant.ui.Activities.SumUpBaseActivity.onOptionsItemSelected(SumUpBaseActivity.java:95)
       at android.app.Activity.onMenuItemSelected(Activity.java:3245)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
       at android.view.View.performClick(View.java:5656)
       at android.view.View$PerformClick.run(View.java:22452)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by sstasi95** [comment]
Hi @mjafartp,

Unfortunately I was not able to reproduce your issue.
The exception is thrown inside SumUp native SDK, so if the problem is still happening you should probably file an issue at [https://github.com/sumup/sumup-android-sdk/issues](url).

Simone
