### ISSUE TITLE
Android crash in combination with FilePicker

### ISSUE THREAD

**Issue by rivella50** [PurpleSoftSrl/sumup_flutter_plugin#25]
I have this very special app crash when aborting a FilePicker->pickFiles action on Android by clicking the native back button, if the Sumup package is installed.
The error log looks like this:
```
I/FilePickerDelegate( 8742): User cancelled the picker request
D/SumupPlugin( 8742): onActivityResult - RequestCode: 24176 - Result Code: 0
D/AndroidRuntime( 8742): Shutting down VM
E/AndroidRuntime( 8742): FATAL EXCEPTION: main
E/AndroidRuntime( 8742): Process: com.test.staging, PID: 8742
E/AndroidRuntime( 8742): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=24176, result=0, data=null} to activity {com.test.staging/com.example.riverpod.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property currentOperation has not been initialized
E/AndroidRuntime( 8742): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime( 8742): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
E/AndroidRuntime( 8742): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 8742): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 8742): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8742): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8742): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/AndroidRuntime( 8742): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8742): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8742): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8742): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime( 8742): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8742): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8742): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 8742): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property currentOperation has not been initialized
E/AndroidRuntime( 8742): 	at io.purplesoft.sumup.SumupPlugin.onActivityResult(SumupPlugin.kt:204)
E/AndroidRuntime( 8742): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 8742): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 8742): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:802)
E/AndroidRuntime( 8742): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 8742): 	at android.app.Activity.dispatchActivityResult(Activity.java:8385)
E/AndroidRuntime( 8742): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
E/AndroidRuntime( 8742): 	... 13 more
I/Process ( 8742): Sending signal. PID: 8742 SIG: 9
```
It's enough that Sumup plugin is installed, but never used. The only thing i added in Manifest.xml is this:
```
<activity
               android:name="net.openid.appauth.RedirectUriReceiverActivity"
               tools:node="merge"
               android:exported="true" tools:ignore="MissingClass"/>
```
As soon as i uninstall the Sumup package the mentioned abort action works fine.
The code to reproduce this is simple:
```
// call this from a button click and hit the native back button after the picking dialog has opened
void pick() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles();

    if (result != null) {
      File file = File(result.files.single.path!);
      print(file.path);
    } else {
      print('no file selected');
    }
  }
```
pubspec.yaml:
```
file_picker: ^4.6.1
sumup: ^0.4.0
```
I hope you have a fix for this. Thanks a lot.

**Comment by rivella50** [comment]
I've just seen, that there is version 0.5.0, where this problem doesn't occur anymore. Therefore i will close this issue.
