### ISSUE TITLE
compatibility with Theme.Appcompat and Theme.MaterialComponents

### ISSUE THREAD

**Issue by andreatristano** [PurpleSoftSrl/sumup_flutter_plugin#41]
I am unable to figure out if the app is crashing because of incompatibility with the app theme.

Actually i have to use this kind of android configuration in styles.xml in order to use other packages:

<resources>
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>

and i think this is not working with sumup package.

Anyway, this is the logcat output (package name omitted and substituted with com.********* for privacy and security reasons)

onAttachedToEngine
16:35:07.108  D  onMethodCall: initSDK
16:35:07.155  D  onMethodCall: login
16:35:07.159  I  START u0 {cmp=com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity (has
                 extras) mCallingUid=10270} from uid 10270
16:35:07.166  D  isSupportZoomModeWithPolicyLocked: target
                 = com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity
16:35:07.169  D  add ActivityRecord{2eda08 u0
                 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity} t70} to mActivityRecordSum
                 = Counter{com.*********/.MainActivity(1) com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity(1) }
16:35:07.169  D  getStartingWindowType: newTask=false, taskSwitch=false, processRunning=true, allowTaskSnapshot=true, activityCreated=false, snapshot=null, record:ActivityRecord{2eda08
                 u0 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity} t70}
16:35:07.169  D  isSupportZoomModeWithPolicyLocked: target
                 = com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity
16:35:07.186  I  setFocusedApplication displayId=0 ActivityRecord{2eda08 u0
                 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity} t70}
16:35:07.426  E  FATAL EXCEPTION: main
                 Process: com.*********, PID: 30289
                 java.lang.RuntimeException: Unable to resume activity
                 {com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity}: java.lang.IllegalMonitorStateException: object
                 not locked by thread before wait()
                 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5060)
                 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5103)
                 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
                 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:240)
                 	at android.os.Looper.loop(Looper.java:351)
                 	at android.app.ActivityThread.main(ActivityThread.java:8381)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                 Caused by: java.lang.IllegalMonitorStateException: object not locked by thread before wait()
                 	at java.lang.Object.wait(Native Method)
                 	at com.sumup.base.common.location.GoogleLocationServicesManager.requestLocationUpdates(Unknown Source:28)
                 	at com.sumup.base.common.location.GoogleLocationServicesManager.startLocationScanning(Unknown Source:31)
                 	at com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity.onResume(SourceFile:11)
                 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1550)
                 	at android.app.Activity.performResume(Activity.java:8540)
                 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5042)
                 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5103) 
                 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60) 
                 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:240) 
                 	at android.os.Looper.loop(Looper.java:351) 
                 	at android.app.ActivityThread.main(ActivityThread.java:8381) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
16:35:07.437  W    Force finishing activity com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity
16:35:07.599  D  remove ActivityRecord{2eda08 u0
                com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity} t-1 f}} to
                 mActivityRecordSum = Counter{com.*********/.MainActivity(1) }
16:35:07.625  D  reparent to null sequence=474, seq[1], name=ActivityRecord{2eda08 u0
                 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity}#474
16:35:07.625  D  ~Layer() sequence=474, name=ActivityRecord{2eda08 u0
                 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity}#474
16:35:07.938  W  Activity top resumed state loss timeout for ActivityRecord{2eda08 u0
                 com.*********/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity} t-1 f}}

**Comment by sstasi95** [comment]
Hi, 

Could you please try to run the example app with your style config to see if it crashes? Just to be sure that is a sumup issue and not some incompatibility issue with other plugins.

**Comment by andreatristano** [comment]
Ciao Simone, sono italiano. Domattina provo e vi metto un update su github
dei risultati,  grazie per la pronta risposta

Il Ven 1 Set 2023, 12:52 Simone Stasi ***@***.***> ha scritto:

**Comment by andreatristano** [comment]
Hello, i tested Your example app, Theme compatibility is not the issue. Thank You for Your quick support
